# Uncomment the next line to define a global platform for your project
# platform :ios, '10'

target 'editorTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for editorTest
  pod 'iOSPhotoEditor', :path => '../'
  # so when we make separate changes, they don't appear after building in the main project
  pod 'SwiftLint'
end
